//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zooshop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int Category { get; set; }
        public int Cost { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhotoString { get; set; }
        public byte[] ProductPhotoByte { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
